predefined:
  image:
    types:
      - name: thumbnail
        height: 200
        width: 200
        quality: 50
        scaleType: FILL
        fillColor: /#000000
        type: JPG
      - name: banner
        height: 200
        width: 400
        quality: 75
        scaleType: FILL
        fillColor: /#000000
        type: PNG

source-root-url:

aws:
  s3-endpoint:
  s3-region:
  access-key:
  secret-key:

logdb:
  endpoint:
  name:
  username:
  password:

server:
  error:
    include-message: always